insert into WINERY.POSITION (POSITIONID, POSITIONNAME)
values  (1, 'Fullstack Developer'),
        (2, 'Data Scientist'),
        (3, 'Industrial Automation Engineer'),
        (4, 'Team Lead'),
        (5, 'embedded'),
        (6, 'QA Engineer'),
        (7, 'Fullstack SDET (Test Engineer)'),
        (8, 'Data engineer'),
        (9, 'Software engineer'),
        (10, 'Microsoft Dynamics 365 Fin&Ops Technical Consultant'),
        (11, 'QA engineer'),
        (12, 'Test Otomasyonu'),
        (13, 'Embedded Software Eng. '),
        (14, 'software test automation engineer'),
        (15, 'Network/Sistem M�hendisi'),
        (16, 'Dwh bi developer'),
        (17, 'I.T Recruiter '),
        (18, 'Test otomasyon uzman?'),
        (19, 'Position'),
        (20, 'DevOps Engineer'),
        (21, 'iOS Developer'),
        (22, 'Tester'),
        (23, 'UI/UX Designer'),
        (24, 'Computer Vision/Software Engineer'),
        (25, 'Test M�hendisi '),
        (26, 'Koordinat�r '),
        (27, 'C++ developer '),
        (28, 'Pentester (Siber G�venlik Uzman?)'),
        (29, 'Veri ambari ve is zekasi danismani'),
        (30, 'qa'),
        (31, 'data services engineer'),
        (32, 'Arge'),
        (33, 'Intern data engineer'),
        (34, 'Garson'),
        (35, 'Architect / Mimar'),
        (36, 'Growth marketer'),
        (37, 'QA'),
        (38, 'SR.QA'),
        (39, 'Project Manager'),
        (40, 'Frontend a??rl?kl? Fullstack'),
        (41, 'Embedded Software Developer'),
        (42, 'Test Otomasyon M�hendisi '),
        (43, 'Siber G�venlik Uzman?'),
        (44, 'P'),
        (45, 'SAP teknik dan??man '),
        (46, 'Embedded software dev'),
        (47, 'Analist'),
        (48, 'ML engineer'),
        (49, 'Software QA Engineer'),
        (50, 'Machine Learning Engineer'),
        (51, 'Embedded Software'),
        (52, 'Data Scientist '),
        (53, 'Computer vision researcher'),
        (54, 'Dijital �retim sistemleri geli?tirici '),
        (55, 'Data scientist '),
        (56, 'Monitoring'),
        (57, 'Big data engineer'),
        (58, 'PO'),
        (59, 'Makine m�hendisi '),
        (60, 'Backend Developer'),
        (61, 'Sap sistem uzman?'),
        (62, 'Qa'),
        (63, 'Siber G�venlik'),
        (64, 'CRM Developer'),
        (65, 'Network specialist'),
        (66, 'Oracle Database Administrator'),
        (67, 'Avukat'),
        (68, 'Frontend Developer'),
        (69, 'Data Analyst'),
        (70, 'QA '),
        (71, 'AI Research Engineer'),
        (72, 'Qa engineer'),
        (73, 'Intern'),
        (74, 'Koordinat�r'),
        (75, 'Business Intelligence Consultant'),
        (76, 'WordPress dev. '),
        (77, 'Mobile Developer'),
        (78, 'Y�netici / M�d�r'),
        (79, 'ML Engineer'),
        (80, 'Game Developer / Oyun Geli?tirici'),
        (81, 'Test otomasyon'),
        (82, 'Backend Dev/ Team Manager'),
        (83, 'Dr. �?r. �yesi '),
        (84, 'Data Engineer'),
        (85, 'Tester '),
        (86, 'Siber g�venlik uzman? '),
        (87, 'QA/Test Automation'),
        (88, 'ERP Yaz?l?mc?'),
        (89, 'Marketing'),
        (90, 'Makine yaz?l?m? otomasyonu (plc)'),
        (91, 'Sosyal Medya Uzman?'),
        (92, 'Embedded'),
        (93, 'Embedded '),
        (94, 'PLC & Robotic'),
        (95, 'Tasar?mc?'),
        (96, 'Product manager'),
        (97, 'Test m�hendisi'),
        (98, 'ABAP Developer'),
        (99, 'Project manager'),
        (100, 'Red Team Engineer'),
        (101, 'Business Intelligence Specialist'),
        (102, 'Takim lideri'),
        (103, 'Tak?m lideri'),
        (104, 'Embedded software engineer '),
        (105, 'M�hendislik analiz'),
        (106, 'Sql developer'),
        (107, 'Test Otomasyon'),
        (108, 'Embedded Software Engineer');